name: bill_split
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  firebase_analytics: ^10.1.5
  cloud_firestore: ^4.4.4
  fluid_bottom_nav_bar: ^1.4.0
  get_storage: ^2.1.1
  flutter_expandable_fab: ^1.7.1
  dropdown_button2: ^2.0.0
  flutter_expanded_tile: ^0.3.7
  h_alert_dialog: ^1.1.2
  flutter_platform_alertbox: ^0.0.4
  pull_to_refresh: ^2.0.0


dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

