// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLkPKagQTvi6UG2x8NYinqScgmdqakNio',
    appId: '1:868211008345:web:8ccf9eb1f85c358e37a248',
    messagingSenderId: '868211008345',
    projectId: 'aesthetic-honor-334516',
    authDomain: 'aesthetic-honor-334516.firebaseapp.com',
    storageBucket: 'aesthetic-honor-334516.appspot.com',
    measurementId: 'G-9FWSTXZLCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN5L87Zvza9g2csrLuQU2XFq_wL2zIA70',
    appId: '1:868211008345:android:e70d7839ab6725bf37a248',
    messagingSenderId: '868211008345',
    projectId: 'aesthetic-honor-334516',
    storageBucket: 'aesthetic-honor-334516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeMY5A0L29Jt10SbBxDEXjguc0D3rCr3k',
    appId: '1:868211008345:ios:1bc4d29135220e0e37a248',
    messagingSenderId: '868211008345',
    projectId: 'aesthetic-honor-334516',
    storageBucket: 'aesthetic-honor-334516.appspot.com',
    iosClientId: '868211008345-n1612r511lr4cb6r8ukpojr4a6tkmm1k.apps.googleusercontent.com',
    iosBundleId: 'com.ikp.billsplit.billSplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeMY5A0L29Jt10SbBxDEXjguc0D3rCr3k',
    appId: '1:868211008345:ios:1bc4d29135220e0e37a248',
    messagingSenderId: '868211008345',
    projectId: 'aesthetic-honor-334516',
    storageBucket: 'aesthetic-honor-334516.appspot.com',
    iosClientId: '868211008345-n1612r511lr4cb6r8ukpojr4a6tkmm1k.apps.googleusercontent.com',
    iosBundleId: 'com.ikp.billsplit.billSplit',
  );
}
